from time import sleep

from userbot import CMD_HELP, CMD_HANDLER as cmd
from userbot.utils import Xa_cmd


@Xa_cmd(pattern="bii$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("BIIIIIIIIIII⭐")
        sleep(1)
        await e.edit("💜⭐✨🌠")
        sleep(1)
        await e.edit("💜💜💜💜")
        sleep(1)
        await e.edit("⭐✨🌠💜")
        sleep(1)
        await e.edit("BII🌠✨")
        sleep(1)
        await e.edit("BINTANG💜💜")
        sleep(1)
        await e.edit("🌠⭐💜✨")
        sleep(1)
        await e.edit("BII CANTIK💜")
        sleep(1)
        await e.edit("💜⭐🌠✨")
        await e.edit("💜💜💜💜")
        await e.edit("⭐🌠✨💜")
        await e.edit("BII IMUT")
        sleep(1)
        await e.edit("BIIII LUCU")
        sleep(1)
        await e.edit("BI SUKA UNGU")
        sleep(1)
        await e.edit("✨💜🌠⭐")
        sleep(1)
        await e.edit("BII BAIK")
        sleep(1)
        await e.edit("CUMA MAU BILANG")
        sleep(1)
        await e.edit("BII CANTIK BANGET💜")
        sleep(1)
        await e.edit("TAPI NGESELIN HUU🤣")
        sleep(1)
        await e.edit("BII BINTANG ⭐")
        sleep(1)
        await e.edit("CUMA MAU BILANG")
        sleep(1)
        await e.edit("BII LUCU")
        sleep(1)
        await e.edit("BIIIIIIII⭐⭐⭐")
        sleep(1)
        await e.edit("POKOKNYA MAU BII💞")


@Xa_cmd(pattern="orgil(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ANJING ADA ORANG GILA.....`")
    sleep(1)
    await typew.edit("`ORANG GILAAAAAA!!`")
    sleep(1)
    await typew.edit("`🏃                        🤸`")
    await typew.edit("`🏃                       🤸`")
    await typew.edit("`🏃                      👨‍🦽`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃   `LARII`          🤾`")
    await typew.edit("`🏃                   🤾`")
    await typew.edit("`🏃                  🤾`")
    await typew.edit("`🏃                 🤾`")
    await typew.edit("`🏃                🤾`")
    await typew.edit("`🏃               🤺`")
    await typew.edit("`🏃              🏊`")
    await typew.edit("`🏃             🏊`")
    await typew.edit("`🏃            🏄`")
    await typew.edit("`🏃           🤾`")
    await typew.edit("`🏃PULUPULU   🧚`")
    await typew.edit("`🏃           ⛹️`")
    await typew.edit("`🏃            ⛹️`")
    await typew.edit("`🏃             🤺`")
    await typew.edit("`🏃              🥴`")
    await typew.edit("`🏃               🏃`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃                 🤸`")
    await typew.edit("`🏃                  🤸`")
    await typew.edit("`🏃                   🤸`")
    await typew.edit("`🏃                    🤸`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃  Huh-Huh           🏃`")
    await typew.edit("`🏃                   🤑`")
    await typew.edit("`🏃                  🙈`")
    await typew.edit("`🏃                 ⛹️`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃               🤴`")
    await typew.edit("`🏃              🐖`")
    await typew.edit("`🏃             🐖`")
    await typew.edit("`🏃            🥴`")
    await typew.edit("`🏃           🥴`")
    await typew.edit("`🏃          🤡`")
    await typew.edit("`🏃         🤭`")
    await typew.edit("`CAPE BANGET ANJING!!!`")
    sleep(1)
    await typew.edit("`🏃       🏃`")
    await typew.edit("`🏃      🤾`")
    await typew.edit("`🏃     🏃`")
    await typew.edit("`🏃    🏃`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🐖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@Xa_cmd(pattern="ass(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Salam dulu biar sopan....`")
    sleep(2)
    await typew.edit("`A`")
    await typew.edit("`As`")
    await typew.edit("`Ass`")
    await typew.edit("`Assa`")
    await typew.edit("`Assal`")
    await typew.edit("`Assala`")
    await typew.edit("`Assalam`")
    await typew.edit("`Assalamu`")
    await typew.edit("`Assalamu'a`")
    await typew.edit("`Assalamu'al`")
    await typew.edit("`Assalamu'ala`")
    await typew.edit("`Assalamu'alai`")
    await typew.edit("`Assalamu'alaik`")
    await typew.edit("`Assalamu'alaiku`")
    await typew.edit("`Assalamu'alaikum`")
    sleep(3)
    await typew.edit("**YANG GA JAWAB, FIX ATHEISS!!**")
# Create by myself @ram-ubot


CMD_HELP.update({
    "animasi7": f"`{cmd}gabut` ; `{cmd}orgil`\
    \nUsage: ntahlah gabut doang.\
    \n\n`{cmd}ass`\
    \nUsage: Salam dulu biar sopan."
})

CMD_HELP.update({
    "animasi8": f"`{cmd}cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`{cmd}bii` :\
    \nUsage: Special command for @Aiibiie ."
})
